### PR TITLE
Add native executable support

### PR DESCRIPTION
**Pull request by tms0**
This PR makes the extension compatible with native executable applications.
I did a big refacto, based on what have been done in the liquibase and flyway extensions.

@janknobloch I removed the health check, it was not easy to integrate after the refacto and I'm not confortable with it. Are you ok with that ? We can still try to add it later.

### CODE REVIEW

**Comment by janknobloch** [comment]
hey @tms0 , thanks for your PR, I briefly checked the content and it looks it has way more to it than just the title, instead of adding native support this PR is basically not even a refactoring but a replacement of existing behaviour :-).

e.g. changing from:

- using pre-defined package folder for scanning using mongock to use quarkus to scan for all annotations
- removing configuration parameters recommended by the quarkus community ,e.g. healthcheck on/off and extension on/off
- removing healthchecks alltogether - so basically it breaks functionality and the plugin will no be usable running in kubernetes etc. as one expect the service should not take requests on failed migrations etc.

I suggest we add the native behaviour (and just that) in a separate PR, then talk about integrating other features e.g. feature flag / config settings like use-package-scanning, vs, scan-package as a fixed value, healthcheck reasoning e.g. when should the pod be up and running and when should the pod be in a ready state e.g. what happens on migration errors? 

merging as is would render the extension to be harmful at least IMO on production environments as the quarkus application will be up and running after a failed migration, e.g. when using a newer data model in the code and the migration to that new data model has failed, the application is up, running ready to take requests and erroring as the models are most likely not compatible.

WDYT?

**Comment by tms0** [comment]
Hi @janknobloch,

I know it's a big refacto, I write it before you publish your code and I tried to not just replace what you have done, but making this extension compatible with native mode necessary changes a lot of things.

We can't use package scanning in a native executable, this is why I removed it. And IMHO, why keeping it if the migration classes are detected automatically ?

About the ability to disable the extension, I didn't removed it, the property is now in the `MongockBuildTimeConfig`.

About the healthcheck logic, maybe my refacto changed something but if the migration fails, the application will not start, so for me the healthcheck is not useful anymore. This is the same in the flyway and liquibase extensions. Maybe I can add a test to cover this behavior ?

**Comment by janknobloch** [comment]
hey @tms0 

thanks for your comment, 

as I think you have a clear and different vision of where this extension should go, I suggest I just remove the main branch and MR so you can start fresh pushing your original code without modifications and maintain the extension with your vision in mind? 

Since im not going to use the extension with the planned changes I think its better someone is maintaining it who is actually using it in his/her projects, so if potential issues come up they are spotted easier. Also I don't want to stall any further development here with discussions and argumentations for people they want to use the extension as is.

Please let me know if you agree, so I would do the suggested and inform the quarkus team about ownership afterwards.

BR

**Comment by tms0** [comment]
Thank you for your message and your understanding.

I appreciate your recognition of my vision for the extension. If you really won't use the extension with these modifications, it makes sense to start again from scratch. I am ready to take over and move forward with this project.

Thanks again for your cooperation

**Comment by janknobloch** [comment]
@tms0 closed and resetted main according to my possibilities, best of luck with the extension.

**Pull request closed without merging**
